from pathlib import Path

CODE: str

def code_repos(root: Path) -> list: ...
def owner(finding: str, root: Path, repos: list) -> str: ...
def partition(findings: dict, root: Path, repos: list) -> tuple: ...
def write_local(repo: str, root: Path, findings: dict, scanned: int) -> int: ...
def scatter(findings: dict, root: Path, files: list) -> tuple: ...
