from _typeshed import Incomplete

REPORT: Incomplete
LEDGERS: Incomplete

def collect(files: list) -> dict: ...
def size_signals(files: list) -> list: ...
def stub_signals(files: list) -> list: ...
def main() -> int: ...
