from _typeshed import Incomplete

TAIL_BYTES: Incomplete

def state_file(session_id: str) -> str: ...
def announced(session_id: str) -> int: ...
def mark(session_id: str, threshold: int) -> None: ...
def find_transcript(raw: dict, session_id: str, cwd: str) -> str: ...
def last_context(path: str) -> int: ...
def message(ctx: int, crossed: int, loud: int) -> str: ...
def main() -> None: ...
