from _typeshed import Incomplete

HERE: Incomplete
CORE: Incomplete
REGISTRY_FILE: Incomplete
PROFILE_FILE: Incomplete
GROUPS: Incomplete
ENFORCEMENT: Incomplete
SCOPES: Incomplete
OFF_ENV: str

def load_registry() -> list: ...
def slugs() -> set: ...
def load_profile() -> dict: ...
def is_enabled(slug: str) -> bool: ...
def setting(key: str, default: str = '') -> str: ...
def findings() -> list: ...
def main() -> int: ...
