from _typeshed import Incomplete

WORKSPACE_ROOT: Incomplete

def interpreter() -> str: ...
def posix(path) -> str: ...
def rel(path, root=...) -> str: ...
def secure_dir(path) -> None: ...
def secure_file(path) -> None: ...
