from _typeshed import Incomplete
from pathlib import Path

HOOKS: Incomplete
ROOT_BLOCK: str
INFERRED_TRIGGER: Incomplete

def area_of(path: str) -> str: ...
def trigger_of(area: str) -> tuple: ...
def features() -> list: ...
def matrix(rows: list) -> tuple: ...
def unwired(rows: list) -> list: ...
def containment(root: Path = ...) -> tuple: ...
def mass(root: Path = ..., depth: int = 2) -> list: ...
def scope(root: Path = ...) -> dict: ...
