#!/usr/bin/env python3
# A code repo drawn from its own declarations — the same page shell as the workspace's, holding
# only the drawings a repo actually has a source for.
#
# Ruled 2026-08-20 (Lucas): every code repo gets an ARCHITECTURE.html, on the same scope line as
# ISSUES.md, and sameness is the starting point because it is cheap to build and cheap to reject.
# He also said to expect the shared shape to fail somewhere, and that WHERE IT FAILS NAMES THE FIRST
# REAL TYPE. It failed immediately and the break is clean:
#
#   transfers — routing (containment, from the generated routing blocks) and mass (git ls-files).
#               Both already took a root argument, so the workspace's own design had anticipated it.
#   does not  — the enforcement matrix, the layer summary, the session lifecycle and the wiring
#               fan-in. All four read core/features.txt and the hook registrations. A repo under
#               code/ declares no features and registers no hooks, so those four are not "missing
#               data" to fill in: they are questions about the ENFORCEMENT LAYER, which exists once.
#
# So the first real type is named: the workspace's picture is about what fires and what is wired;
# a code repo's is about what it is made of. The findings band below is the repo's half of the
# health read — the same question the workspace's summary answers, from the source a repo does have.
import re
from pathlib import Path

import diagram_data as data
import diagram_page as page
import diagram_spine as spine_form
import diagram_treemap as mass_form

SPINE_DEPTH = 3
OUTPUT = 'ARCHITECTURE.html'
_TOTAL = re.compile(r'\*\*(\d+) findings\*\*')
_ROW = re.compile(r'^\| ([^|*][^|]*?) \| (\d+) \|$', re.M)


def findings(root: Path) -> tuple:
    """(total, [(check, count)]) read out of the repo's own ISSUES.md, never recounted here.

    The ledger is generated by the entropy dashboard and is the interface; a second scan would be
    a second number to disagree with the first, which is the drift both tools exist to catch.
    """
    ledger = root / 'ISSUES.md'
    if not ledger.exists():
        return None, []
    text = ledger.read_text(encoding='utf-8')
    total = _TOTAL.search(text)
    rows = [(name.strip(), int(count)) for name, count in _ROW.findall(text) if int(count)]
    return (int(total.group(1)) if total else None), sorted(rows, key=lambda r: -r[1])


def health(root: Path, coverage: dict) -> str:
    """The band above the tabs: what this repo's own ledger says, and how much of it was parsed."""
    total, rows = findings(root)
    if total is None:
        body = ('<p class="q">No <code>ISSUES.md</code> yet — run the entropy dashboard from the '
                'workspace root and it will write one.</p>')
    else:
        cells = ''.join(f'<tr><td>{name}</td><td class="n">{count}</td></tr>' for name, count in rows)
        body = (f'<p class="q">{total} findings in this repo\'s own ledger, worst first. '
                'The count is read from <code>ISSUES.md</code>, never recounted here.</p>'
                f'<table class="findings"><tbody>{cells}</tbody></table>'
                if rows else '<p class="q">Its ledger is clean.</p>')
    return ('<section class="ov"><h2>what this repo carries</h2>' + body
            + f'<p class="q">Routing parsed {coverage["parsed"]} of {coverage["total"]} blocks.</p>'
            '</section>')


def build(root: Path) -> tuple:
    """(html, coverage). Only the drawings this repo has a source for — see the head of this file."""
    nodes, edges, coverage = data.containment(root)
    mass = data.mass(root)
    panels = {'spine': (spine_form.render(nodes, edges, SPINE_DEPTH),
                        spine_form.legend(coverage)),
              'mass': (mass_form.render(mass), mass_form.legend(mass))}
    name = root.name
    return page.render(panels, coverage, data.scope(root), summary=health(root, coverage),
                       title=f'{name} architecture', heading=f'{name} as it is',
                       whole=False), coverage
