# The generated artifacts a session close regenerates, and what happens to each one afterwards.
# Sourced by core/tools/wos/roundup — a FRAGMENT, not a standalone script: it relies on $WORKSPACE,
# $LEAVE_DIRTY, $VERIFY, $VERIFY_CMD and $LOG from the caller.
#
# Extracted 2026-08-20, when the verify block would have been the THIRD copy of the same eight
# lines. Every artifact here follows one rule: regenerate, then commit it — unless the tree holds
# another session's work, in which case report the number and roll the write back, because a
# regenerated file left behind rides into that session's next `git add -A`.

# settle <file> <was_clean> <commit message> — prints the suffix its caller appends to a status line.
# Silent and zero-exit when the artifact did not move, which is the common case and the point:
# deterministic output means a file changes when the WORKSPACE changed, never merely because a
# generator ran.
settle() {
  local file="$1" was_clean="$2" msg="$3"
  git diff --quiet "$file" 2>/dev/null && return 0
  if [ -n "$LEAVE_DIRTY" ]; then
    [ "$was_clean" = 1 ] && git checkout -q -- "$file" 2>/dev/null
    printf ' · reported only, not committed (tree holds another session'\''s work)'
  elif ! { git add "$file" && git commit -q -m "$msg"; }; then
    printf ' · commit failed, %s left dirty' "$file"
  fi
}

# The verification result, into ISSUES.md beside the entropy findings — a red suite and a drift
# finding are both answers to "what is currently untrue that we know about" (core/SCHEMA.md § The
# `.md` type system). This is the only thing that can write it: the suite already ran, and
# re-running it to report it would double the one cost the pre-commit gate exists to keep small.
# The block writer is shared with every other generated block rather than reimplemented in shell.
verify_block() {
  {
    printf '## Verification\n\n'
    printf '> Generated by `core/tools/wos/roundup` at session close. The suite is the authority; '
    printf 'this is its last result, never a claim that it is still true.\n\n'
    printf '%s · `%s` · **%s**\n' "$(date +%F)" "${VERIFY_CMD:-no contract}" "$VERIFY"
    if [ "$VERIFY" = "red" ]; then printf '\n```\n'; tail -20 "$LOG"; printf '```\n'; fi
  } | python3 "$WORKSPACE/core/hooks/routing/blocks.py" ISSUES.md verify
}
