def ler_categorias(caminho: str = '/mnt/workspace/code/prog1/recursos/categorias.json'): ...
def ler_pessoas(caminho: str = '/mnt/workspace/code/prog1/recursos/pessoas.txt'): ...
def ler_governo(caminho: str = '/mnt/workspace/code/prog1/recursos/governo.json'): ...
def ler_empresas(caminho: str = 'mp8/recursos/empresas.csv'): ...
def ler_produtos(caminho: str = 'mp8/recursos/produtos.csv'): ...
