from _typeshed import Incomplete

WORKSPACE_ROOT: Incomplete

def test_every_project_declares_its_goal() -> None: ...
def test_a_declared_goal_passes(tmp_path) -> None: ...
def test_a_deliberate_none_passes(tmp_path) -> None: ...
def test_a_missing_declaration_is_flagged(tmp_path) -> None: ...
def test_a_dead_goal_link_is_flagged(tmp_path) -> None: ...
def test_scaffolding_is_not_a_project(tmp_path) -> None: ...
def test_a_non_project_context_is_not_asked(tmp_path) -> None: ...
