from _typeshed import Incomplete

WORKSPACE_ROOT: Incomplete
LEDGERS: Incomplete

def test_retired_tokens_come_from_schema() -> None: ...
def test_no_retired_token_survives() -> None: ...
def test_the_law_may_name_what_it_retires(tmp_path) -> None: ...
def test_retired_token_in_a_filename_is_a_hit(tmp_path) -> None: ...
def test_a_longer_word_is_not_a_substring_hit(tmp_path) -> None: ...
def test_item_slugs_read_item_position_only(tmp_path) -> None: ...
def test_sibling_namespaces_may_repeat_a_slug(tmp_path) -> None: ...
def test_same_slug_in_two_ledgers_is_a_duplicate(tmp_path) -> None: ...
def test_no_item_lives_in_two_ledgers() -> None: ...
