from _typeshed import Incomplete

SCRIPT: Incomplete

def test_new_context_bearing_subdir_gets_allowlisted(tmp_path) -> None: ...
def test_context_free_subdir_is_left_ignored(tmp_path) -> None: ...
def test_exception_listed_subdir_is_never_added(tmp_path) -> None: ...
def test_already_allowed_subdir_is_untouched(tmp_path) -> None: ...
def test_running_twice_is_idempotent(tmp_path) -> None: ...
def test_own_repo_subdir_gets_the_narrow_triplet_not_a_bare_unignore(tmp_path) -> None: ...
