from classes.empresa import Empresa as Empresa
from classes.pessoa import Pessoa as Pessoa

def simular_sociedade(pessoas, empresas, governo, categorias) -> None: ...
def simular_empresa(empresa) -> None: ...
def simular_pessoa(pessoa, empresas, categorias) -> None: ...
