def calc_preco(empresa): ...
def calc_disponibilidade(empresa): ...
def comprar(pessoa, empresa) -> None: ...
def escolher_melhor(categoria, empresas, orcamento): ...
def escolher_barato(categoria, empresas, orcamento): ...
def calc_renda_mensal(pessoa): ...
def distribuir_produtos(empresas, governo, produtos) -> None: ...
