#!/usr/bin/env python3
# The entropy report: what the dashboard's findings look like on the page.
#
# Split from entropy-dashboard.py 2026-07-30, when that file crossed the 150-line warn.
# A tool that reports size signals is a poor place to ignore one.
from datetime import date


def _rel(path, root) -> str:
    return str(path).replace(f'{root}/', '')


SECTIONS = (
    ('types', 'Off-allowlist `.md` types', 'route via core/SCHEMA.md § four disposal routes'),
    ('inventories', 'CONTEXT.md hand-written inventories', 'the routing block owns inventory'),
    ('naming', 'Naming and placement', 'kebab-case ASCII, types where their scope allows'),
    ('goals', 'Projects not declaring their goal', 'line 3 of a code/ CONTEXT.md'),
    ('wiki', 'Wiki-links naming nothing', 'a [[slug]] is a goal file or an item in one'),
    ('retired', 'Retired tokens still alive', 'a rename is unfinished until these are zero'),
    ('citations', 'Roadmap item numbers cited outside a roadmap',
     'a closed item is deleted — cite the SPECS.md/SCHEMA.md section that owns the rule'),
    ('duplicates', 'Items claimed by two ledgers', 'v1 criterion 2 — an item lives in one place'),
    ('size', 'Size signals', 'a signal for review, never a cap — do not summarize to fit'),
    ('stubs', 'Source files with no interface stub',
     'the read gate only fires when a stub exists — a missing one turns it off silently'),
    ('fanout', 'Directories holding too many files',
     'splitting costs one hop — pay it only when it removes more table than it adds'),
    ('finished', 'Prose describing finished work',
     'git is the history — cut it, or rewrite it as present-tense state'),
    ('undescribed', 'Unanswered scaffold placeholders',
     'a generator asked a question — answer it at the source, never by cutting the marker'),
    ('misplaced', 'Constraints trapped in a CONTEXT.md head',
     'the only enforced-read type — move the contract to a sibling SPECS.md'),
    ('branches', 'Repos on an unmerged feature branch',
     'promote when the work is green, or say which reason applies — /roundup Phase 5'),
    ('remotes', 'Remote branches already merged into their base',
     'safe to delete, and outward-facing — `git -C <repo> push origin --delete <branch>`, Lucas'),
)


def render(findings: dict, scanned: int, root) -> str:
    total = sum(len(findings[key]) for key, _, _ in SECTIONS)
    out = ['# entropy',
           '> Generated by `core/hooks/entropy/entropy-dashboard.py`. Do not edit.',
           '',
           f'{date.today().isoformat()} · {scanned} tracked files scanned · '
           f'**{total} findings**', '',
           '| Check | Findings |', '|-------|----------|']
    out += [f'| {title} | {len(findings[key])} |' for key, title, _ in SECTIONS]
    for key, title, note in SECTIONS:
        items = findings[key]
        out += ['', f'## {title}', '', f'*{note}*', '']
        out += ['Clean.'] if not items else [
            f'- {_rel(i.splitlines()[0], root)}' for i in sorted(items)]
    return '\n'.join(out) + '\n'
