from _typeshed import Incomplete
from collections import defaultdict as defaultdict
from pathlib import Path as Path

MAX_DAYS: int

def parse_owns(path): ...
def governing_repo(rel_path): ...
def harvest(repo): ...

class Attention:
    missing: Incomplete
    def __init__(self, goal_files, owns_by_slug=None) -> None: ...
    def count(self, slug, days): ...
    def last_touch(self, slug): ...
    def area_count(self, slugs, days): ...
