from _typeshed import Incomplete
from pathlib import Path as Path

LEDGERS: Incomplete

def test_retired_tokens_come_from_schema() -> None: ...
def test_no_retired_token_survives() -> None: ...
def test_the_law_may_name_what_it_retires(tmp_path) -> None: ...
def test_retired_token_in_a_filename_is_a_hit(tmp_path) -> None: ...
def test_a_longer_word_is_not_a_substring_hit(tmp_path) -> None: ...
def test_item_slugs_read_item_position_only(tmp_path) -> None: ...
def test_sibling_namespaces_may_repeat_a_slug(tmp_path) -> None: ...
def test_same_slug_in_two_ledgers_is_a_duplicate(tmp_path) -> None: ...
def test_no_item_lives_in_two_ledgers() -> None: ...
def test_goal_vocabulary_holds_files_and_their_items(tmp_path) -> None: ...
def test_a_wiki_link_to_an_item_resolves(tmp_path) -> None: ...
def test_a_wiki_link_naming_nothing_is_flagged(tmp_path) -> None: ...
def test_every_wiki_link_in_the_workspace_resolves() -> None: ...
def test_memory_links_are_exempt_but_its_retired_tokens_are_not() -> None: ...
