from _typeshed import Incomplete
from pathlib import Path as Path

def test_every_project_declares_its_goal() -> None: ...
def test_a_declared_goal_passes(tmp_path) -> None: ...
def test_a_deliberate_none_passes(tmp_path) -> None: ...
def test_a_missing_declaration_is_flagged(tmp_path) -> None: ...
def test_a_dead_goal_link_is_flagged(tmp_path) -> None: ...
def test_scaffolding_is_not_a_project(tmp_path) -> None: ...
def test_a_non_project_context_is_not_asked(tmp_path) -> None: ...

HEAD_WARN: Incomplete

def test_an_over_size_head_carrying_a_constraint_is_flagged(tmp_path) -> None: ...
def test_a_long_head_that_only_navigates_is_clean(tmp_path) -> None: ...
def test_a_thin_head_may_carry_a_constraint(tmp_path) -> None: ...
def test_an_existing_sibling_spec_changes_the_advice(tmp_path) -> None: ...
def test_only_context_files_are_checked(tmp_path) -> None: ...
def test_the_generated_block_is_not_part_of_the_head(tmp_path) -> None: ...
def test_a_generated_mirror_is_not_flagged(tmp_path) -> None: ...
