from _typeshed import Incomplete
from pathlib import Path as Path

spec: Incomplete
type_gate: Incomplete
SCHEMA: Incomplete

def test_law_comes_from_schema() -> None: ...
def test_scopes_come_from_schema() -> None: ...
def test_allowlisted_name_passes(tmp_path) -> None: ...
def test_invented_type_is_blocked(tmp_path) -> None: ...
def test_lowercase_instance_is_never_checked(tmp_path) -> None: ...
def test_harness_mandated_name_is_exempt(tmp_path) -> None: ...
def test_ascii_tree_is_flagged(tmp_path) -> None: ...
def test_inventory_heading_is_flagged(tmp_path) -> None: ...
def test_path_bullets_are_flagged(tmp_path) -> None: ...
def test_two_path_bullets_are_allowed(tmp_path) -> None: ...
def test_naming_convention_globs_are_allowed(tmp_path) -> None: ...
def test_generated_routing_block_is_not_an_inventory(tmp_path) -> None: ...
def test_clean_context_passes(tmp_path) -> None: ...
def test_non_context_file_is_not_inventory_checked(tmp_path) -> None: ...
