from _typeshed import Incomplete

TOOL: Incomplete

def test_the_summary_counts_the_same_workspace_the_matrix_does() -> None: ...
def test_the_two_halves_of_the_split_lose_nothing_between_them() -> None: ...
def test_a_declared_layer_holding_nothing_is_still_drawn() -> None: ...
def test_a_harness_mirror_is_excluded_by_rule_not_by_a_list() -> None: ...
def test_every_finding_is_a_gap_rather_than_a_shape() -> None: ...
def test_a_finding_standing_on_convention_is_labelled_inferred() -> None: ...
def test_the_summary_needs_no_click(tmp_path) -> None: ...
