from pathlib import Path

def label(att: dict) -> str: ...
def blocks(message: dict) -> list: ...
def walk(path: Path) -> dict: ...
def attribute(session: dict) -> tuple: ...
def median(values: list) -> float: ...
