from conftest import WORKSPACE_ROOT as WORKSPACE_ROOT
from pathlib import Path as Path

def test_an_all_empty_interface_column_is_dropped(tmp_path) -> None: ...
def test_a_column_with_one_real_value_survives(tmp_path) -> None: ...
def test_file_and_description_are_never_dropped(tmp_path) -> None: ...
def test_test_symbols_are_not_listed_as_api(tmp_path) -> None: ...
def test_a_shared_fixture_is_still_api(tmp_path) -> None: ...
def test_a_production_symbol_in_a_test_directory_still_appears(tmp_path) -> None: ...
def test_every_scanned_extension_can_be_described() -> None: ...
def test_a_shell_script_is_described_below_its_shebang(tmp_path) -> None: ...
def test_preserved_descriptions_survive_a_narrower_table() -> None: ...
