from _typeshed import Incomplete
from entropy_corpus import enforcement_paths as enforcement_paths, tracked_files as tracked_files
from pathlib import Path

ITEM_SLUG: Incomplete

def retired_hits(files: list, retired: dict, exempt: set) -> list: ...
def item_slugs(path: Path) -> set: ...
def duplicate_slugs(namespaces: dict) -> dict: ...

WIKI_LINK: Incomplete

def goal_vocabulary(goals_dir: Path) -> set: ...
def wiki_link_hits(files: list, vocabulary: set, exempt: set) -> list: ...
