from _typeshed import Incomplete
from pathlib import Path

SCANNED: Incomplete
SKIP_DIRS: Incomplete
ITEM_SLUG: Incomplete

def tracked_files(root: Path, nested: bool = False) -> list: ...
def nested_repos(root: Path, depth: int = 3) -> list: ...

ENFORCEMENT: Incomplete

def enforcement_paths(root: Path) -> set: ...
def retired_hits(files: list, retired: dict, exempt: set) -> list: ...
def item_slugs(path: Path) -> set: ...
def duplicate_slugs(namespaces: dict) -> dict: ...
