from _typeshed import Incomplete
from pathlib import Path

HARNESS_MANDATED: Incomplete
UPPERCASE_MD: Incomplete

def check_name(path: Path, allowed: set, exempt: set) -> str | None: ...
def staged_added_files() -> list: ...
def failures_for(path: Path, allowed: set, exempt: set, scopes: dict) -> list: ...
def main() -> int: ...
