from _typeshed import Incomplete
from pathlib import Path

HARNESS_MANDATED: Incomplete
UPPERCASE_MD: Incomplete
ROUTING_START: str
TREE_GLYPH: Incomplete
PATH_BULLET: Incomplete
INVENTORY_HEADING: Incomplete

def check_name(path: Path, allowed: set, exempt: set) -> str | None: ...
def check_inventory(path: Path) -> str | None: ...
def staged_added_files() -> list: ...
def failures_for(path: Path, allowed: set, exempt: set, scopes: dict) -> list: ...
def main() -> int: ...
