from _typeshed import Incomplete
from pathlib import Path

WORKSPACE_ROOT: Incomplete
OPENER: Incomplete
REDIRECT: Incomplete
TEE: Incomplete

def targets(line: str) -> list: ...
def in_workspace(target: str, cwd: str) -> Path | None: ...
def written_paths(command: str, cwd: str) -> list: ...
def main() -> int: ...
