from _typeshed import Incomplete

MAX_LINES: int
BLOCK_KEYWORD: Incomplete
CONTINUES: Incomplete

def rtk_rewrite(command: str) -> str | None: ...
def delegate(command: str) -> None: ...
def splittable(lines: list[str]) -> bool: ...
def main() -> int: ...
