from _typeshed import Incomplete

HOOKS: Incomplete
SHIMS: Incomplete

def test_every_shim_names_at_least_one_canonical_script() -> None: ...
def test_opencode_spawns_only_scripts_that_exist() -> None: ...
def test_copilot_spawns_only_scripts_that_exist() -> None: ...
