from _typeshed import Incomplete

POSTEDIT: Incomplete
PRECOMMIT: Incomplete
EMIT_KEYS: Incomplete

def test_jsconfig_template_carries_no_emit_keys() -> None: ...
def test_tracked_jsconfigs_carry_no_emit_keys() -> None: ...
def test_scaffolded_tsconfig_with_dot_outdir_declares_exclude() -> None: ...
def test_js_declarations_are_generated_per_file_not_per_project() -> None: ...
def test_no_generated_stub_sits_in_a_doubled_path() -> None: ...
