from _typeshed import Incomplete
from pathlib import Path

SHARD_FIELD: Incomplete
ITEM: Incomplete
SLUG: Incomplete
NEEDS_LUCAS: str
EMPTY_CELL: Incomplete
SHARD_COLUMNS: Incomplete

def shard_facts(path: Path) -> dict: ...
def render_table(headers: tuple, rows: list, always: tuple) -> str: ...
def shards_of(index: Path) -> list: ...
def index_for(path: Path) -> Path | None: ...
def build_shard_rows(shards: list) -> str: ...
