from _typeshed import Incomplete
from pathlib import Path

SHARD_FIELD: Incomplete
ITEM: Incomplete
LUCAS_ITEM: Incomplete
SLUG: Incomplete
EMPTY_CELL: Incomplete
ITEM_HEADLINE: Incomplete
SHARD_COLUMNS: Incomplete

def shard_facts(path: Path) -> dict: ...
def render_table(headers: tuple, rows: list, always: tuple) -> str: ...
def shards_of(index: Path) -> list: ...
def index_for(path: Path) -> Path | None: ...
def item_headlines(path: Path) -> list: ...
def build_open_items(shards: list) -> str: ...
def build_shard_rows(shards: list) -> str: ...
