from _typeshed import Incomplete

SETUP: Incomplete
DEPS: Incomplete

def test_every_setup_step_maps_to_a_declared_feature() -> None: ...
def test_every_dependency_feature_is_a_declared_feature() -> None: ...
def test_a_skill_slug_names_the_skill_file() -> None: ...
def test_every_row_is_complete_and_in_its_closed_set() -> None: ...
def test_every_declared_feature_has_an_answer() -> None: ...

SKILL_MIRROR: str

def test_a_row_claiming_to_be_wired_really_is() -> None: ...
def test_an_unknown_slug_fails_open() -> None: ...
def test_the_ablation_switch_turns_one_feature_off(monkeypatch) -> None: ...
def test_the_cli_agrees_with_this_file() -> None: ...
def test_the_wired_gates_actually_consult_the_law() -> None: ...
