from _typeshed import Incomplete

TOOL: Incomplete

def test_every_declared_feature_reaches_the_matrix() -> None: ...
def test_an_unwired_feature_is_shown_rather_than_omitted() -> None: ...
def test_coverage_names_a_block_it_could_not_read(tmp_path) -> None: ...
def test_the_inferred_edges_are_labelled_as_inferred(tmp_path) -> None: ...
def test_the_page_carries_everything_it_needs(tmp_path) -> None: ...
def test_the_output_is_deterministic(tmp_path) -> None: ...
def test_check_reports_stale_and_current(tmp_path) -> None: ...
def test_the_switch_is_honest(tmp_path) -> None: ...
def test_the_treemap_tiles_its_whole_area() -> None: ...
def test_the_spine_stops_at_its_depth_and_says_so() -> None: ...
def test_the_summary_counts_the_same_workspace_the_matrix_does() -> None: ...
def test_a_declared_layer_holding_nothing_is_still_drawn() -> None: ...
def test_a_harness_mirror_is_excluded_by_rule_not_by_a_list() -> None: ...
def test_every_finding_is_a_gap_rather_than_a_shape() -> None: ...
def test_a_finding_standing_on_convention_is_labelled_inferred() -> None: ...
def test_the_summary_needs_no_click(tmp_path) -> None: ...
