# T1 the workspace picture: the generator behind ARCHITECTURE.html.
# Zero-token, no network, no browser.
#
# WHAT THESE GUARD, and it is not "does it draw something pretty": the picture's whole claim is
# that it cannot be more wrong than its sources. That claim dies two ways — a source silently
# dropped, so the drawing looks complete while a subtree is missing, and an inferred edge drawn
# like a declared one. Both are checked here. A drawing nobody can trust is worse than none,
# because it is believed.
import subprocess

import diagram_data as data
import diagram_health as health
import diagram_matrix as matrix_form
import diagram_overview as overview_form
import diagram_spine as spine_form
import diagram_treemap as mass_form
import feature_law as law
import tool_law
from conftest import WORKSPACE_ROOT

TOOL = WORKSPACE_ROOT / 'core/tools/wos/diagram/architecture'


def _run(*args, off=''):
    env = {'PATH': '/usr/bin:/bin', law.OFF_ENV: off} if off else None
    return subprocess.run([str(TOOL), *args], capture_output=True, text=True,
                          cwd=WORKSPACE_ROOT, env=env)


def _page(tmp_path):
    out = tmp_path / 'ARCHITECTURE.html'
    result = _run('--out', str(out))
    assert result.returncode == 0, result.stdout + result.stderr
    return out.read_text(encoding='utf-8'), result.stdout


def test_every_declared_feature_reaches_the_matrix():
    """Nothing is silently dropped. A feature missing from the picture is invisible exactly where
    the picture is supposed to make it visible, which is how a diagram starts lying."""
    rows, _columns, _cells = data.matrix(data.features())
    assert {row['slug'] for row in rows} == law.slugs()


def test_an_unwired_feature_is_shown_rather_than_omitted():
    """`features --findings` counts what cannot be switched off; a drawing of wiring would hide
    those rows by construction, so it marks them instead."""
    rows, columns, cells = data.matrix(data.features())
    html = matrix_form.render(rows, columns, cells, data.trigger_of)
    for row in data.unwired(rows):
        assert row['slug'] in html
    assert 'unwired' in html


def test_coverage_names_a_block_it_could_not_read(tmp_path):
    """Fail-loud, not fail-quiet: a routing block without its sentinels is COUNTED and NAMED."""
    root = tmp_path / 'ws'
    (root / 'sub').mkdir(parents=True)
    (root / 'AGENTS.md').write_text('# root\n<!-- routing:start -->\n'
                                    '| [`sub/`](sub/CONTEXT.md) | a subtree |\n'
                                    '<!-- routing:end -->\n', encoding='utf-8')
    (root / 'sub/CONTEXT.md').write_text('# sub\n> no routing block at all\n', encoding='utf-8')
    subprocess.run(['git', 'init', '-q'], cwd=root, check=True)
    subprocess.run(['git', 'add', '-A'], cwd=root, check=True)

    _nodes, edges, coverage = data.containment(root)
    assert coverage['total'] == 2 and coverage['parsed'] == 1
    assert coverage['unparsed'] == ['sub/CONTEXT.md']
    assert ('', 'sub') in edges


def test_the_inferred_edges_are_labelled_as_inferred(tmp_path):
    """No machine-readable hook-trigger registry exists yet, so the firing moment is a convention
    and the page must say so. The day the registry lands this test changes with it."""
    when, inferred = data.trigger_of('core/hooks/checks')
    assert inferred and when != 'unknown'
    html, _out = _page(tmp_path)
    assert 'inferred' in html


def test_the_page_carries_everything_it_needs(tmp_path):
    """Self-contained or it is not an asset inside the workspace: it opens from a file:// path on a
    machine with no network, under any provider."""
    html, _out = _page(tmp_path)
    for offender in ('http://', 'https://', '<script', 'src=', '<link'):
        assert offender not in html
    assert html.startswith('<!-- ARCHITECTURE.html — generated by')


def test_the_output_is_deterministic(tmp_path):
    """--check compares the file, so a timestamp or a commit sha in the page would make every
    session close report a stale picture and commit a diff that means nothing."""
    first, _out = _page(tmp_path)
    second, _out = _page(tmp_path)
    assert first == second


def test_check_reports_stale_and_current(tmp_path):
    out = tmp_path / 'ARCHITECTURE.html'
    assert _run('--out', str(out), '--check').returncode == 1       # absent is stale
    _page(tmp_path)
    assert _run('--out', str(out), '--check').returncode == 0
    out.write_text(out.read_text(encoding='utf-8') + '<!-- hand edit -->', encoding='utf-8')
    stale = _run('--out', str(out), '--check')
    assert stale.returncode == 1 and 'STALE' in stale.stdout


def test_the_switch_is_honest(tmp_path):
    """core/SPECS.md § AD-14: the row claims a switch, so throwing it must move the observable.
    Off means no picture written and the tool's own refusal code — not a quiet exit 0 that an
    ablation arm would read as success."""
    out = tmp_path / 'off.html'
    result = _run('--out', str(out), off='diagram')
    assert result.returncode == tool_law.OFF_EXIT and not out.exists()


def test_the_treemap_tiles_its_whole_area():
    """A squarify bug shows up as blank canvas, which reads as 'nothing is there' rather than as a
    drawing error — the one failure mode of this form that a viewer cannot spot."""
    rows = [r for r in data.mass() if r[2] > 0]
    rects = mass_form._layout([size for _n, _f, size in rows], 0, 0,
                              mass_form.WIDTH, mass_form.HEIGHT)
    assert len(rects) == len(rows)
    covered = sum(w * h for _x, _y, w, h in rects)
    assert abs(covered - mass_form.WIDTH * mass_form.HEIGHT) < 1


def test_the_spine_stops_at_its_depth_and_says_so():
    """Overview first: the whole tree at once is the hairball the cap exists to prevent, and a cap
    that hides what it cut is the same lie as dropping a node."""
    nodes, edges, _coverage = data.containment()
    html = spine_form.render(nodes, edges, max_depth=1)
    assert 'sit deeper than level 1' in html


def test_the_summary_counts_the_same_workspace_the_matrix_does():
    """One source of truth. The summary aggregates the matrix's own rows rather than counting the
    registry a second time — two counts of one thing are free to disagree, and the day they do the
    page contradicts itself in the two places a reader compares first."""
    rows, _columns, _cells = data.matrix(data.features())
    layered = sum(total for _layer, _strength, total in health.by_layer(rows))
    assert layered == sum(len(law.groups(row)) for row in rows)
    assert {layer for layer, _s, _t in health.by_layer(rows)} == law.GROUPS


def test_a_declared_layer_holding_nothing_is_still_drawn():
    """`agents` and `flows` are declared layers with no feature in them. A grid built from what
    exists cannot show what does not, so the rows come from the declared set."""
    rows, _columns, _cells = data.matrix(data.features())
    layers = health.by_layer(rows)
    empty = [layer for layer, _s, total in layers if not total]
    assert empty, 'expected at least one declared-but-unbuilt layer'
    html = overview_form.render(layers, [])
    for layer in empty:
        assert layer in html


def test_a_harness_mirror_is_excluded_by_rule_not_by_a_list():
    """A provider's mirrored tree is not this workspace's rot to fix. The rule is "top-level dotted
    directory", so a harness nobody has heard of yet is covered the day it lands — a hardcoded list
    would start reporting it as an orphan instead."""
    assert health.harness_owned('.some-future-harness/skills')
    assert not health.harness_owned('core/tools/wos')
    assert not any(d.startswith('.') for d, _n in health.orphans())


def test_every_finding_is_a_gap_rather_than_a_shape():
    """The regression for the mistake this list was born with. "28 of 68 features enforce nothing"
    counted 15 skills, 7 tools and 6 recording hooks — features that serve when called instead of
    pushing — and reported the capability half of the workspace as dead weight. A findings list
    whose biggest number is not a problem teaches its reader to stop believing the rest of it."""
    rows, _columns, _cells = data.matrix(data.features())
    _nodes, _edges, coverage = data.containment()
    texts = ' '.join(f['text'] for f in health.findings(rows, coverage))
    assert 'enforce nothing' not in texts
    assert 'exactly one feature' not in texts


def test_a_finding_standing_on_convention_is_labelled_inferred():
    """Same rule the matrix already keeps: the hook firing moments are the one region no file
    declares, and a summary is exactly where an inferred number would be mistaken for a measured
    one."""
    rows, _columns, _cells = data.matrix(data.features())
    _nodes, _edges, coverage = data.containment()
    items = health.findings(rows, coverage)
    inferred = [f for f in items if f['inferred']]
    assert len(inferred) == 1 and 'firing' in inferred[0]['text']
    assert 'inferred' in overview_form.render(health.by_layer(rows), items)


def test_the_summary_needs_no_click(tmp_path):
    """The page's whole defect was that its two most-asked questions were behind detail. The
    summary renders outside the tab strip, so it is on screen before any interaction."""
    html, _stdout = _page(tmp_path)
    assert html.index('class="heat"') < html.index('<div class="tabs">')
