from _typeshed import Incomplete

ROOT: Incomplete
TOTAL: Incomplete

def test_every_code_repo_has_its_own_ledger() -> None: ...
def test_the_root_total_equals_the_sum_of_the_local_ledgers() -> None: ...
def test_the_index_lists_every_repo_that_has_a_ledger() -> None: ...
def test_a_finding_lands_in_the_repo_that_owns_its_path() -> None: ...
def test_the_innermost_repo_wins_when_one_nests_inside_another() -> None: ...
def test_papers_and_branches_stay_pooled_at_the_root() -> None: ...
def test_core_and_brain_stay_with_the_workspace_repo() -> None: ...
def test_partition_loses_no_finding() -> None: ...
