def carregar_pessoas(endereco): ...
def adicionar_pessoa(nome, patrimonio, salario, pessoas) -> None: ...
def remover_pessoa(nome, pessoas) -> None: ...
def salvar_pessoas(endereco, pessoas) -> None: ...
